### ISSUE TITLE
git version 2.7.4 no recurrence this vulnerability

### ISSUE THREAD

**Issue by acusp** [twistlock/gitPocDiff#1]
In my test, it's just hidden `[8m`, the `git diff` command output is as follows:

```
* Must always return a value Hidden > */printf("Insert bad backdoor here...!\n");/*
```

My git version is 2.7.4, I do not know if this is the reason?

**Comment by zelivans** [comment]
Hi, my demonstration was done with 2.7.4 as well.
What terminal emulator are you using?

**Comment by acusp** [comment]
My terminal emulator is Konsole which not reproduce this vulnerability.
And my computer OS is Mint 18.3, I successful reproduce this vulnerability on it native GNOME terminal.
Thank you for your reply!

**Comment by zelivans** [comment]
Perhaps console does not implement the hidden text formatting sequence. Testing with Konsole 15.12.3 this seems to be the case :man_shrugging:
